[tmp] after installing additional dependencies sudo apt-get install -y squashfuse fuse2fs gocryptfs
currently still not working

1. build singularity containers for bohb and dummy_problem
2. delete database if you already created one
3. create cluster configs with the python script, use BOHB config
> python smacbenchmarking/container/create_cluster_configs.py +optimizer/bohb=bohb +problem/DUMMY=config 'seed=range(1,2)' --multirun

4 run test:
> export SLURM_JOB_ID=1
> ./start_container_noctua2.sh

fails with

2024-02-20 15:52:31,215  | py-experimenter - INFO     | All configured executions finished.
Runner container finished
Starting problem container
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.
INFO:    instance started successfully
API is not yet ready (HTTP status: 000). Retrying in 5 seconds...
API is up and running!
Host Found
Starting optimizer container
Traceback (most recent call last):
  File "/home/ruhkopf/PycharmProjects/SMACBenchmarking/smacbenchmarking/container/container_optimizer.py", line 33, in <module>
    experimenter = PyExperimenter(
  File "/usr/local/lib/python3.10/site-packages/py_experimenter/experimenter.py", line 93, in __init__
    self.config = PyExperimenterCfg.extract_config(experiment_configuration_file_path, logger=self.logger)
  File "/usr/local/lib/python3.10/site-packages/py_experimenter/config.py", line 353, in extract_config
    config = omegaconf.OmegaConf.load(config_path)
  File "/usr/local/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 190, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "/home/ruhkopf/PycharmProjects/SMACBenchmarking/smacbenchmarking/container/py_experimenter.cfg", line 2, column 1
Run Finished
INFO:    Stopping problem instance of /home/ruhkopf/PycharmProjects/SMACBenchmarking/DUMMY_Problem.sif (PID=41258)